### ISSUE TITLE
POH storage: Boss lair jars

### ISSUE THREAD

**Issue by Thource** [Thource/dude-wheres-my-stuff#30]

**Comment by Nick2bad4u** [comment]
Was just about to add this myself but its here.

**Comment by hawkins** [comment]
Saw your comment on the duped issue, I've got a couple jars I could use for testing this. If you're open to dealing with amateur Java contributors in the review, I'd be happy to take this one on. First thought is it looks like it'll entail enumerating the jars in PlayerOwnedHouseStorageType since the interface looks so similar to the magic wardrobe, from there I'll compare with the magic wardrobe's storage to see what else I'm missing from the pattern. I'll dig in and see where to go from there but if I already sound far off I'd appreciate any pointers!

**Comment by Thource** [comment]
> Saw your comment on the duped issue, I've got a couple jars I could use for testing this. If you're open to dealing with amateur Java contributors in the review, I'd be happy to take this one on. First thought is it looks like it'll entail enumerating the jars in PlayerOwnedHouseStorageType since the interface looks so similar to the magic wardrobe, from there I'll compare with the magic wardrobe's storage to see what else I'm missing from the pattern. I'll dig in and see where to go from there but if I already sound far off I'd appreciate any pointers!

Hey, absolutely happy for you to take a crack at this, as a start I’d run runelite in developer mode, open the inventory inspector and var inspector, then add/remove jars from the display and see if anything changes in either the inventory inspector or var inspector :)

**Comment by Nick2bad4u** [comment]
> > Saw your comment on the duped issue, I've got a couple jars I could use for testing this. If you're open to dealing with amateur Java contributors in the review, I'd be happy to take this one on. First thought is it looks like it'll entail enumerating the jars in PlayerOwnedHouseStorageType since the interface looks so similar to the magic wardrobe, from there I'll compare with the magic wardrobe's storage to see what else I'm missing from the pattern. I'll dig in and see where to go from there but if I already sound far off I'd appreciate any pointers!
> 
> Hey, absolutely happy for you to take a crack at this, as a start I’d run runelite in developer mode, open the inventory inspector and var inspector, then add/remove jars from the display and see if anything changes in either the inventory inspector or var inspector :)

Now thats teamwork boys!
