### ISSUE TITLE
Death pile timer resets when hopping worlds

### ISSUE THREAD

**Issue by ste-h** [Thource/dude-wheres-my-stuff#55]

**Comment by Thource** [comment]
Hey, can you please provide as much detail as you can around the circumstances of your death, location, how long the client was open, what you did after the death, etc please? This issue keeps coming up every so often but it only happens some times, so it's really hard to figure out why it's happening.

**Comment by ste-h** [comment]
Took a clip of it happening, happens every time I hop so didn't think to include much info
I pick nettles to die in edge

here's a clip of it happening: https://streamable.com/d4pjeg
Expires in 39 minutes is correct, but upon hopping it goes to 53 years ago, to 60 minutes

**Comment by Thource** [comment]
This happens because there is no reliable way for the plugin to get your account's played time, the current workaround is to ensure that the "Character summary" (brown star) tab is active in the quest interface at least once per session before you die and when checking how long is left.

I'll be changing the behaviour of deathpiles so that there is a choice in the settings between this current behaviour (accurate timers, but requires the brown star tab to be active at least once per login/hop) or static timers (60 minutes from point of death, only ticks down while logged in, on runelite, with the plugin enabled - meaning that if you log in for 5 minutes on mobile, the timer will be wrong)
